# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1cb5f8f052f0d6a73a4b934fdaaf47a5"
application_url = "https://jame-vu.cloud"
embedded = true
name = "remix-base"
handle = "remix-base"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://jame-vu.cloud/auth/callback",
  "https://jame-vu.cloud/auth/shopify/callback",
  "https://jame-vu.cloud/api/auth/callback"
]

[pos]
embedded = false
